package java_0129;

class UserException extends Exception{

	private int port = 772;
	public UserException(String msg){
		super(msg);
	}
	public UserException(String msg, int port){
		super(msg);
		this.port = port;
	}
	public int getPort(){
		return port;
	}
}

public void test1(String[] n) throws UserException{
	    System.out.println("Test1");
	    if(n.length < 1)
	        throw new UserException("아무것도 없다네"); // 강제 exception 발생
	    else
	        throw new UserException("최종 예선",703); // 강제 exception 발생
}

class UserExceptionEx {

	public static void main(String[] args) {
		UserException ue = new UserException(args[0])
		if(args[0]>0){
			new throw 
		}

	}

}
